# Generated by Django 4.2.17 on 2024-12-20 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="название"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=30, unique=True, verbose_name="слаг"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="описание"),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=500, verbose_name="очки рейтинга"
                    ),
                ),
                (
                    "bootstrap_icon",
                    models.SlugField(default="trophy", verbose_name="иконка"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователи",
                    ),
                ),
            ],
            options={
                "verbose_name": "достижение",
                "verbose_name_plural": "достижения",
            },
        ),
    ]
