# Generated by Django 4.2.16 on 2025-02-11 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("achievements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="achievements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователи",
            ),
        ),
    ]
