# Generated by Django 5.0.2 on 2024-12-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="exam",
        ),
        migrations.AddField(
            model_name="user",
            name="exams",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="practice.exam",
                verbose_name="выбранные экзамены",
            ),
        ),
    ]
