# Generated by Django 4.2.16 on 2024-12-17 18:18

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_friendrequest"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
