# Generated by Django 4.2.17 on 2024-12-17 16:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_friendrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-score"],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
