# Generated by Django 4.2.16 on 2024-12-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_alter_dayofweek_day"),
        ("users", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="days_of_lessons",
            field=models.ManyToManyField(
                related_name="users",
                to="planning.dayofweek",
                verbose_name="Дни занятий",
            ),
        ),
    ]
