# Generated by Django 4.2.16 on 2024-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_options_user_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="score_planning",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
