# Generated by Django 4.2.17 on 2024-12-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_score_planning"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="последний вход"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_time_spent",
            field=models.PositiveIntegerField(
                default=0, verbose_name="время на сайте"
            ),
        ),
    ]
