# Generated by Django 4.2.16 on 2025-02-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        max_length=40, verbose_name="текст ответа"
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ",
                "verbose_name_plural": "ответы",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="название"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="слаг")),
            ],
            options={
                "verbose_name": "экзамен",
                "verbose_name_plural": "экзамены",
            },
        ),
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="подтема"),
                ),
                (
                    "number",
                    models.PositiveIntegerField(verbose_name="номер подтемы"),
                ),
            ],
            options={
                "verbose_name": "подтема",
                "verbose_name_plural": "подтемы",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_text_html",
                    models.TextField(verbose_name="текст задания"),
                ),
                (
                    "task_solution_html",
                    models.TextField(verbose_name="текст решения"),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="practice.subtopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "задание",
                "verbose_name_plural": "задания",
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expiration_time",
                    models.DateTimeField(verbose_name="время окончания"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, to="practice.task", verbose_name="задания"
                    ),
                ),
            ],
            options={
                "verbose_name": "вариант",
                "verbose_name_plural": "варианты",
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="тема"),
                ),
                (
                    "task_number",
                    models.PositiveIntegerField(verbose_name="номер задания"),
                ),
                (
                    "is_answered",
                    models.BooleanField(
                        help_text="есть ли четкий ответ на задание",
                        verbose_name="из развернутой части",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="practice.exam",
                        verbose_name="экзамен",
                    ),
                ),
            ],
            options={
                "verbose_name": "тема",
                "verbose_name_plural": "темы",
            },
        ),
        migrations.AddField(
            model_name="subtopic",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopics",
                to="practice.theme",
                verbose_name="тема",
            ),
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        verbose_name="максимальный балл"
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(verbose_name="набранный балл"),
                ),
                (
                    "duration",
                    models.DurationField(verbose_name="время решения"),
                ),
                (
                    "full_variant",
                    models.BooleanField(
                        default=False, verbose_name="полный вариант"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practice.exam",
                        verbose_name="экзамен",
                    ),
                ),
            ],
            options={
                "verbose_name": "решение",
                "verbose_name_plural": "решения",
            },
        ),
    ]
