# Generated by Django 4.2.16 on 2024-12-02 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="название"),
                ),
            ],
            options={
                "verbose_name": "экзамен",
                "verbose_name_plural": "экзамены",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_text_html",
                    models.TextField(verbose_name="текст задания"),
                ),
                (
                    "task_solution_html",
                    models.TextField(verbose_name="текст решения"),
                ),
                (
                    "is_answered",
                    models.BooleanField(
                        default=False,
                        help_text="есть ли четкий ответ на задание",
                        verbose_name="из развернутой части",
                    ),
                ),
            ],
            options={
                "verbose_name": "задание",
                "verbose_name_plural": "задания",
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="тема"),
                ),
                (
                    "task_number",
                    models.PositiveIntegerField(verbose_name="номер задания"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="practice.exam",
                        verbose_name="экзамен",
                    ),
                ),
            ],
            options={
                "verbose_name": "тема",
                "verbose_name_plural": "темы",
            },
        ),
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="подтема"),
                ),
                (
                    "number",
                    models.PositiveIntegerField(verbose_name="номер подтемы"),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="practice.theme",
                        verbose_name="тема",
                    ),
                ),
            ],
            options={
                "verbose_name": "подтема",
                "verbose_name_plural": "подтемы",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        max_length=40, verbose_name="текст ответа"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="practice.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ",
                "verbose_name_plural": "ответы",
            },
        ),
    ]
