# Generated by Django 4.2.16 on 2024-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_answered",
        ),
        migrations.AddField(
            model_name="theme",
            name="is_answered",
            field=models.BooleanField(
                default=False,
                help_text="есть ли четкий ответ на задание",
                verbose_name="из развернутой части",
            ),
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiration_time", models.DateTimeField()),
                (
                    "tasks",
                    models.ManyToManyField(blank=True, to="practice.task"),
                ),
            ],
            options={
                "verbose_name": "вариант",
                "verbose_name_plural": "варианты",
            },
        ),
    ]
