# Generated by Django 4.2.17 on 2024-12-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_remove_task_is_answered_theme_is_answered_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="is_answered",
            field=models.BooleanField(
                help_text="есть ли четкий ответ на задание",
                verbose_name="из развернутой части",
            ),
        ),
    ]
