# Generated by Django 4.2.16 on 2025-02-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.CharField(
                max_length=300, verbose_name="текст ответа"
            ),
        ),
    ]
