# Generated by Django 4.2.16 on 2024-12-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_alter_theme_is_answered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="subtopic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="practice.subtopic",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="variant",
            name="expiration_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
