# Generated by Django 4.2.16 on 2024-12-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_alter_theme_is_answered"),
        ("practice", "0004_task_subtopic_alter_variant_expiration_time"),
    ]

    operations = []
