# Generated by Django 4.2.16 on 2025-02-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_alter_answer_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtopic",
            name="name",
            field=models.CharField(max_length=300, verbose_name="подтема"),
        ),
    ]
