# Generated by Django 4.2.16 on 2024-12-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0005_merge_20241208_1658"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="slug",
            field=models.SlugField(
                default="", unique=True, verbose_name="слаг"
            ),
        ),
    ]
