# Generated by Django 4.2.16 on 2024-12-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0006_exam_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="слаг"),
        ),
    ]
