# Generated by Django 4.2.16 on 2024-12-09 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("practice", "0008_alter_variant_expiration_time_solution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="duration",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="solution",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
