# Generated by Django 4.2.16 on 2024-12-10 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0010_alter_solution_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
