# Generated by Django 4.2.16 on 2024-12-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0011_variant_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
