# Generated by Django 4.2.16 on 2024-12-10 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("practice", "0012_alter_variant_date_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solution",
            options={
                "verbose_name": "решение",
                "verbose_name_plural": "решения",
            },
        ),
        migrations.AddField(
            model_name="variant",
            name="fine",
            field=models.IntegerField(
                default=0,
                help_text="вычитается из максимального балла",
                verbose_name="штраф",
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="date",
            field=models.DateField(
                auto_now_add=True, verbose_name="дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="duration",
            field=models.DurationField(verbose_name="время решения"),
        ),
        migrations.AlterField(
            model_name="solution",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="practice.exam",
                verbose_name="экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="full_variant",
            field=models.BooleanField(
                default=False, verbose_name="полный вариант"
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="max_score",
            field=models.PositiveIntegerField(
                verbose_name="максимальный балл"
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="score",
            field=models.PositiveIntegerField(verbose_name="набранный балл"),
        ),
        migrations.AlterField(
            model_name="solution",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="время создания"
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="expiration_time",
            field=models.DateTimeField(verbose_name="время окончания"),
        ),
        migrations.AlterField(
            model_name="variant",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, to="practice.task", verbose_name="задания"
            ),
        ),
    ]
