# Generated by Django 4.2.16 on 2024-12-10 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0013_alter_solution_options_variant_fine_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="fine",
        ),
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practice.task",
                        verbose_name="задание",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fines",
                        to="practice.variant",
                        verbose_name="вариант",
                    ),
                ),
            ],
        ),
    ]
