# Generated by Django 4.2.16 on 2024-12-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayofweek",
            name="day",
            field=models.IntegerField(
                choices=[
                    (1, "Понедельник"),
                    (2, "Вторник"),
                    (3, "Среда"),
                    (4, "Четверг"),
                    (5, "Пятница"),
                    (6, "Суббота"),
                    (7, "Воскресенье"),
                ],
                unique=True,
            ),
        ),
    ]
