# Generated by Django 4.2.16 on 2024-12-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_visitedday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayofweek",
            name="day",
            field=models.IntegerField(
                choices=[
                    (0, "Понедельник"),
                    (1, "Вторник"),
                    (2, "Среда"),
                    (3, "Четверг"),
                    (4, "Пятница"),
                    (5, "Суббота"),
                    (6, "Воскресенье"),
                ],
                unique=True,
            ),
        ),
    ]
