# Generated by Django 4.2.17 on 2024-12-14 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("practice", "0014_remove_variant_fine_fine"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="заголовок"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="practice.exam",
                        verbose_name="экзамен",
                    ),
                ),
            ],
            options={
                "verbose_name": "тест",
                "verbose_name_plural": "тесты",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="вопрос")),
                (
                    "correct_answer",
                    models.CharField(
                        max_length=255, verbose_name="правильный ответ"
                    ),
                ),
                ("options", models.JSONField(verbose_name="варианты ответа")),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="preparation.test",
                        verbose_name="тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "задание",
                "verbose_name_plural": "задания",
            },
        ),
    ]
