# Generated by Django 4.2.17 on 2024-12-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preparation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["order"],
                "verbose_name": "задание",
                "verbose_name_plural": "задания",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("test", "order")},
        ),
    ]
