# Generated by Django 4.2.17 on 2024-12-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0015_alter_solution_user"),
        ("preparation", "0002_alter_task_options_task_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="order",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="test",
            unique_together={("exam", "order")},
        ),
    ]
