# Generated by Django 4.2.17 on 2024-12-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preparation", "0002_useranswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
