# Generated by Django 4.2.17 on 2024-12-17 11:38

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("preparation", "0003_test_order_alter_task_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="options",
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
